version: "3.5"

services:
  php_fpm:
    build: ./services/php-fpm/
    container_name: leads_php_fpm
    working_dir: /var/www/leads
    networks:
      - app_network
    volumes:
      - ./../:/var/www/leads

  nginx:
    build: ./services/nginx
    container_name: leads_nginx
    working_dir: /var/www/leads
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/var/www/leads
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: leads_mysql
    networks:
      - app_network
    environment:
      - MYSQL_DATABASE=docker_app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret

  mailhog:
    build: ./services/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge