version: "3.5"

services:
  php_fpm:
    build: ./services/php-fpm/
    container_name: <app-name>_php_fpm
    working_dir: /var/www/<app-name>
    networks:
      - app_network
    volumes:
      - ./../:/var/www/<app-name>

  nginx:
    image: nginx:1.15
    container_name: <app-name>_nginx
    working_dir: /var/www/<app-name>
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/<app-name>
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    container_name: <app-name>_mysql
    networks:
      - app_network
    environment:
      - MYSQL_DATABASE=docker_app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=secret

  mailhog:
    build: ./services/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge